#!/usr/bin/env bash

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

# Frontend for HTTP - Listen on port 80 and redirect to HTTPS
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    acl is_holberton hdr(host) -i www.futurecoders.tech
    redirect scheme https if is_holberton
    default_backend http_back

# Frontend for HTTPS - Listen on port 443
frontend https_front
    bind *:443 ssl crt /etc/letsencrypt/live/www.futurecoders.tech/fullchain.pem privkey /etc/letsencrypt/live/www.futurecoders.tech/privkey.pem
    reqadd X-Forwarded-Proto:\ https
    acl is_root path -i /
    acl is_holberton hdr(host) -i www.futurecoders.tech
    use_backend www-backend if is_root is_holberton
    default_backend http_back

# Backend for HTTP requests
backend http_back
    balance roundrobin
    server 420856-web-01 3.85.168.165:80 check
    server 420856-web-02 100.24.72.68:80 check

# Backend for HTTPS requests
backend www-backend
    balance roundrobin
    server 420856-web-01 3.85.168.165:80 check
    server 420856-web-02 100.24.72.68:80 check
