#!/usr/bin/env bash
# Transfers a file from client to server

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning input arguments to variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Disable strict host key checking and transfer the file
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"

