#!/usr/bin/env bash
# Automates the process of setting up a 301 redirect on Nginx

# Add the redirect rule
sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
