#!/usr/bin/env bash
# Configure Nginx to serve a custom 404 page

# Install Nginx if it's not already installed
apt-get update
apt-get -y install nginx

# Create the custom 404 page
echo '<!DOCTYPE html><html><head><title>Not Found</title></head><body><h1>Ceci n'est pas une page</h1></body></html>' > /var/www/html/404.html

# Update Nginx configuration
sed -i '/server_name _;/a \\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi
