#!/usr/bin/env bash
# sets up a new 404 error page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx 

# Create the main index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart
