#!/usr/bin/env bash
# Customizing Nginx with a 404-error page, updating redirection, and custom HTTP response header

# Updating Packages and Installing Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Updating the existing redirection to https://github.com/besthor
sudo sed -i 's|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|return 301 https://github.com/besthor;|' /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Assuming the error_page 404 /404.html; and location block for /404.html is already set

# Creating an HTTP response header (if not already set)
sudo sed -i '/server_name _;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
