#!/usr/bin/env bash
# Script to set up HAProxy on the lb-01 server.

# Update packages and install HAProxy
echo "Updating packages and installing HAProxy..."
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy for load balancing between web-01 and web-02
echo "Configuring HAProxy for load balancing..."

# Create HAProxy configuration
haproxy_conf="global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_frontend
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 420856-web-01 3.85.168.165:80 check
    server 420856-web-02 100.24.72.68:80 check"

# Write the new configuration to HAProxy config file
echo "$haproxy_conf" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable and restart HAProxy to apply changes
echo "Enabling and restarting HAProxy..."
sudo systemctl enable haproxy
sudo systemctl restart haproxy

echo "HAProxy setup complete."
