#!/usr/bin/env bash
# This script will display the PID along with the process name of processes whose name contain the word "bash".

for pid_path in /proc/[0-9]*; do
    pid=$(basename "$pid_path")
    if [[ -e "/proc/$pid/comm" ]]; then
        comm=$(<"/proc/$pid/comm")
        if [[ "$comm" == *bash* ]]; then
            echo "$pid $comm"
        fi
    fi
done
