#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.

for pid in /proc/[0-9]*; do
  if [[ -f "$pid/comm" ]]; then
    comm=$(cat "$pid/comm")
    if [[ $comm == *"bash"* ]]; then
      echo "$(<"${pid##/proc/}/stat" awk '{print $1}') $comm"
    fi
  fi
done
