#!/usr/bin/env bash
# This script kills the process running the 4-to_infinity_and_beyond script

pid=$(ps aux | grep '[4]-to_infinity_and_beyond' | awk '{print $2}')
if [ ! -z "$pid" ]; then
  kill "$pid"
fi
