#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process without using kill or killall

# shellcheck disable=SC2039  # pkill is not part of POSIX, but we can disable that check
pkill -f 4-to_infinity_and_beyond
