#!/usr/bin/env bash
# This script runs indefinitely, printing a message and catching SIGTERM signals

handle_sigterm() {
  echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
