#!/usr/bin/env bash
# This script implements the FizzBuzz problem

for number in {1..100}; do
    # Check if number is a multiple of 3 and 5
    if (( number % 3 == 0 && number % 5 == 0 )); then
        echo "FizzBuzz"
    # Check if number is a multiple of 3
    elif (( number % 3 == 0 )); then
        echo "Fizz"
    # Check if number is a multiple of 5
    elif (( number % 5 == 0 )); then
        echo "Buzz"
    else
        echo $number
    fi
done
