#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Get the list of IP addresses and filter out the IPv4 addresses
ip -4 addr | grep 'inet' | awk '{print $2}' | cut -d/ -f1
